[topic]

[topic.enabled]
type="checkbox"
textLabel="Running"
order=1

[query]

[query.keywords]
type="text"
textLabel="Keywords"
reqired=true
order=1


[query.order_by]
type="select"
textLabel="Order by"
options = [ ["most_relevance","Most relevance"], 
            ["newest","Newest"], 
            ["price_low_to_high","Lowest price"], 
            ["price_high_to_low","Highest price"] ] 
reqired=true
order=2

[query.max_sale_price]
type="number"
textLabel="Max sale price"
order=3

[query.min_sale_price]
type="number"
textLabel="Min sale price"
order=4

[query.category_ids]
type="number"
textLabel="Category IDs"
order=5

[query.latitude]
type="number"
textLabel="Latitude"
order=6

[query.longitude]
type="number"
textLabel="Longitude"
order=7

[query.condition]
type="select"
textLabel="Condition"
options = [ ["",""], 
            ["new","New"], 
            ["as_good_as_new","As good as new"], 
            ["good","Good"], 
            ["fair","Fair"], 
            ["has_given_it_all","Has given it all"]] 
order=8

[query.is_shippable]
type="checkbox"
textLabel="Only products with shipping:"
order=9

#Notification Methods

[ntfy]
type="stringArray"
textLabel="Channels:"
order=1

