#General Configurations arent inside of objects
[enabled]
type="checkbox"
textLabel="Running"

[name]
type="text"
textLabel="Name"


[querys]
type="objectsArray"

[querys.keywords]
type="text"
textLabel="Keywords"
reqired=true



[querys.order_by]
type="select"
textLabel="Order by"
options = [ ["most_relevance","Most relevance"], 
            ["newest","Newest"], 
            ["price_low_to_high","Lowest price"], 
            ["price_high_to_low","Highest price"] ] 
reqired=true


[querys.max_sale_price]
type="number"
textLabel="Max sale price"


[querys.min_sale_price]
type="number"
textLabel="Min sale price"


[querys.category_ids]
type="number"
textLabel="Category IDs"


[querys.latitude]
type="number"
textLabel="Latitude"

[querys.longitude]
type="number"
textLabel="Longitude"


[querys.condition]
type="select"
textLabel="Condition"
options = [ ["",""], 
            ["new","New"], 
            ["as_good_as_new","As good as new"], 
            ["good","Good"], 
            ["fair","Fair"], 
            ["has_given_it_all","Has given it all"]] 

[querys.is_shippable]
type="checkbox"
textLabel="Only products with shipping:"


#Notification Methods

[notifications]

[notifications.ntfy]

[notifications.ntfy.channels]
type="stringArray"
textLabel="Channels:"

[notifications.discord]

[notifications.discord.enabled_webhook]
type="checkbox"
textLabel="Send to Discord"
