[general]
[general.sleepTime]
type="number"
textLabel="Sleep time (s)"
defaultValue=500

#Notification Methods

[ntfy]
[ntfy.domain]
type="text"
textLabel="Token"

[ntfy.token]
type="text"
textLabel="Domain"
