[topic]

[topic.enabled]
type="checkbox"
textLabel="Running"


[query]

[query.keywords]
type="text"
textLabel="Keywords"
reqired=true



[query.order_by]
type="select"
textLabel="Order by"
options = [ ["most_relevance","Most relevance"], 
            ["newest","Newest"], 
            ["price_low_to_high","Lowest price"], 
            ["price_high_to_low","Highest price"] ] 
reqired=true


[query.max_sale_price]
type="number"
textLabel="Max sale price"


[query.min_sale_price]
type="number"
textLabel="Min sale price"


[query.category_ids]
type="number"
textLabel="Category IDs"


[query.latitude]
type="number"
textLabel="Latitude"

[query.longitude]
type="number"
textLabel="Longitude"


[query.condition]
type="select"
textLabel="Condition"
options = [ ["",""], 
            ["new","New"], 
            ["as_good_as_new","As good as new"], 
            ["good","Good"], 
            ["fair","Fair"], 
            ["has_given_it_all","Has given it all"]] 

[query.is_shippable]
type="checkbox"
textLabel="Only products with shipping:"


#Notification Methods

[ntfy]
type="stringArray"
textLabel="Channels:"


